apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-replicaset
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mia-app
  template:
    metadata:
      labels:
        app: mia-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
